/**
 * Mock Data for Pawly Tour Version (/tour)
 * 100% Isolated in-memory sandbox data — zero backend API calls or DB mutations.
 */

// User's own pets for header filter (1 Dog + 1 Cat)
export const TOUR_MY_PETS = [
  {
    id: 'tour_my_dog',
    pet_name: 'Pawly',
    animal_type: 'dog',
    pet_photo: 'https://placedog.net/120/120?id=1',
  },
  {
    id: 'tour_my_cat',
    pet_name: 'Misi',
    animal_type: 'cat',
    pet_photo: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=120&auto=format&fit=crop&q=80',
  },
];

// Demo cards for DISCOVER sandbox (5 pets total: 3 dogs + 2 cats)
export const INITIAL_TOUR_DEMO_PETS = [
  {
    id: 'demo_pet_1',
    pet_name: 'Luna',
    animal_type: 'dog',
    breed: 'Golden Retriever',
    size: 'large',
    pet_age: 2,
    energy_level: 'high',
    temperament: ['friendly', 'playful', 'energetic'],
    about_me: 'Luna loves running around Töölö park and playing fetch with other friendly dogs!',
    pet_photo: 'https://placedog.net/600/400?id=10',
    match_percentage: 98,
    distance_km: 1.2,
    latitude: 60.178,
    longitude: 24.925,
    owner_id: 'demo_owner_1',
    owner_name: 'Mikael Korhonen',
    owner_photo: 'https://i.pravatar.cc/150?u=demo_user_1',
    owner_bio: 'Hey! I live in Töölö and enjoy weekend park walks with Luna.',
  },
  {
    id: 'demo_pet_2',
    pet_name: 'Milo',
    animal_type: 'cat',
    breed: 'Siamese',
    size: 'small',
    pet_age: 3,
    energy_level: 'medium',
    temperament: ['curious', 'gentle', 'affectionate'],
    about_me: 'Milo is a curious cat who loves indoor climbing towers and cozy window watching.',
    pet_photo: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    match_percentage: 95,
    distance_km: 2.4,
    latitude: 60.171,
    longitude: 24.933,
    owner_id: 'demo_owner_2',
    owner_name: 'Aino Nieminen',
    owner_photo: 'https://i.pravatar.cc/150?u=demo_user_2',
    owner_bio: 'Hi! Milo and I live in Kamppi.',
  },
  {
    id: 'demo_pet_3',
    pet_name: 'Bella',
    animal_type: 'dog',
    breed: 'Poodle',
    size: 'medium',
    pet_age: 4,
    energy_level: 'medium',
    temperament: ['smart', 'calm', 'friendly'],
    about_me: 'Bella loves socializing on Sunday mornings near Kaivopuisto!',
    pet_photo: 'https://placedog.net/600/400?id=12',
    match_percentage: 92,
    distance_km: 3.1,
    latitude: 60.158,
    longitude: 24.945,
    owner_id: 'demo_owner_3',
    owner_name: 'Eero Mäkelä',
    owner_photo: 'https://i.pravatar.cc/150?u=demo_user_3',
    owner_bio: 'Hello from Punavuori!',
  },
  {
    id: 'demo_pet_4',
    pet_name: 'Rocky',
    animal_type: 'dog',
    breed: 'French Bulldog',
    size: 'small',
    pet_age: 2,
    energy_level: 'medium',
    temperament: ['playful', 'cuddly', 'stubborn'],
    about_me: 'Rocky is a fun bulldog who loves short walks and making new doggy buddies.',
    pet_photo: 'https://placedog.net/600/400?id=15',
    match_percentage: 89,
    distance_km: 1.8,
    latitude: 60.165,
    longitude: 24.938,
    owner_id: 'demo_owner_4',
    owner_name: 'Henrik Laine',
    owner_photo: 'https://i.pravatar.cc/150?u=demo_user_4',
    owner_bio: 'Hey! Henrik here from Töölö.',
  },
  {
    id: 'demo_pet_5',
    pet_name: 'Cleo',
    animal_type: 'cat',
    breed: 'Maine Coon',
    size: 'large',
    pet_age: 3,
    energy_level: 'low',
    temperament: ['majestic', 'calm', 'sweet'],
    about_me: 'Cleo is a gentle giant cat who loves relaxing sun spots and treats.',
    pet_photo: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&auto=format&fit=crop&q=80',
    match_percentage: 94,
    distance_km: 2.1,
    latitude: 60.174,
    longitude: 24.948,
    owner_id: 'demo_owner_5',
    owner_name: 'Laura Salmi',
    owner_photo: 'https://i.pravatar.cc/150?u=demo_user_5',
    owner_bio: 'Hi! Laura and Cleo here from Kruununhaka.',
  },
];

// Already connected pet for MESSAGES sandbox (separate from Discover cards)
export const MESSAGES_CONNECTED_PET = {
  id: 'connected_pet_oliver',
  pet_name: 'Oliver',
  animal_type: 'dog',
  breed: 'Labrador Retriever',
  size: 'large',
  pet_age: 3,
  energy_level: 'high',
  temperament: ['friendly', 'social', 'gentle'],
  about_me: 'Oliver loves park playdates and swimming!',
  pet_photo: 'https://placedog.net/600/400?id=5',
  match_percentage: 96,
  owner_name: 'Sofia Virtanen',
  owner_photo: 'https://i.pravatar.cc/150?u=sofia_virtanen',
  owner_bio: 'Hi! Sofia and Oliver here. We love outdoor playdates around Kaivopuisto!',
};

// Contextual Pawly speech messages linked to UI triggers
export const PAWLY_CONTEXT_MESSAGES = {
  default: "Hi! I'm Pawly, your guide. Click any button or feature below to explore how Pawly works!",
  view_lists: "In List view, you can browse pet match cards in a clean single-column format.",
  view_both: "In Both view, you can see pet cards and the interactive map side-by-side.",
  view_map: "In Map view, you can see nearby pets and park clusters on an interactive map.",
  pet_avatar_dog: "Showing filtered results for dog buddies nearby!",
  pet_avatar_cat: "Showing filtered results for cat buddies nearby!",
  pet_avatar_both: "Showing filtered results for all pet buddies nearby!",
  connect_click: "Connection request sent! Once accepted, you can start messaging in the Messages tab.",
  remove_click: "Removed card from your recommendations list.",
  tab_discover: "Discover page helps you find compatible playmates for your pets nearby.",
  tab_messages: "Messages page lets you chat in real-time with connected pet owners.",
  tab_profile: "Profile page lets you manage your owner info and add your pets.",
  send_message: "Live chat allows instant messaging between matched pet owners.",
};
